#!/usr/bin/env bash
# ============================================================
# DOQ Local Production Runner
# Runs full stack: MySQL + App + Cron + Caddy (HTTPS)
# Creates test accounts for all roles
# ============================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Config
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${PROJECT_DIR}/.env.production.local"
COMPOSE_FILES="-f ${PROJECT_DIR}/docker-compose.yml -f ${PROJECT_DIR}/docker-compose.production.yml"
DOMAIN="doq.local"
COMPOSE_CMD="docker compose ${COMPOSE_FILES} --env-file ${ENV_FILE}"

# Test Account Config
TEST_PASSWORD="TestAccount123!"
ADMIN_EMAIL="admin@doq.local"
ADMIN_PASS="AdminLocal123!"
ADMIN_TOTP="JBSWY3DPEHPK3PXP"

# ============================================================
# Helper Functions
# ============================================================
log()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success(){ echo -e "${GREEN}[OK]${NC} $*"; }
warn()   { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
step()   { echo -e "\n${CYAN}=== $* ===${NC}\n"; }

check_cmd() { command -v "$1" >/dev/null 2>&1 || error "$1 not found. Install it first."; }

wait_for_health() {
    local service="$1"
    local max_attempts=60
    local attempt=0
    log "Waiting for ${service} to be healthy..."
    while [[ $attempt -lt $max_attempts ]]; do
        local health
        health=$($COMPOSE_CMD ps --format json "$service" 2>/dev/null | jq -r '.[0].Health // "unknown"' 2>/dev/null || echo "unknown")
        if [[ "$health" == "healthy" ]]; then
            success "${service} is healthy"
            return 0
        fi
        sleep 2
        ((attempt++))
    done
    error "${service} did not become healthy in time"
}

# ============================================================
# Main
# ============================================================
clear
echo -e "${CYAN}"
cat << 'EOF'
╔══════════════════════════════════════════════════════════╗
║  DOQ - Local Production Runner                          ║
║  MySQL + Express + Cron + Caddy (HTTPS)                 ║
║  Auto-creates test accounts for all roles               ║
╚══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# 1. Check prerequisites
step "Checking prerequisites"
check_cmd docker
check_cmd docker compose
check_cmd jq
check_cmd openssl
success "All commands available"

# 2. Create .env.production.local if not exists
step "Setting up environment file"
if [[ ! -f "$ENV_FILE" ]]; then
    log "Creating ${ENV_FILE}..."
    cat > "$ENV_FILE" <<'ENVEOF'
# ============================================================
# DOQ LOCAL PRODUCTION - Auto-generated by run.sh
# ============================================================
DOQ_ENV_FILE=.env.production.local
NODE_ENV=production
PORT=3000
APP_PORT=3000
DOQ_DOMAIN=doq.local
PUBLIC_URL=https://doq.local
TRUST_PROXY=1

DB_HOST=db
DB_PORT=3306
DB_USER=doq_user
DB_PASSWORD=LocalProdDBPass123!
DB_NAME=DOQ
MYSQL_ROOT_PASSWORD=LocalProdRootPass123!
MYSQL_BIND_ADDRESS=127.0.0.1
MYSQL_BIND_PORT=3306

JWT_SECRET=LocalProdJWTSecretKey64CharactersLongForSecurityTestingOnly1234567890
RUN_MIGRATIONS=true
WAIT_FOR_DB=true

CRON_ENABLED=true
CRON_INTERVAL_SECONDS=3600
DAILY_REPORT_ENABLED=true
PURGE_REPORTED_COMPLETED_ORDERS=true

COMMISSION_APPROVED=false
CHEF_COMMISSION_PERCENT=7
DELIVERY_COMMISSION_PERCENT=7
DELIVERY_COMMISSION_BASIS=order_total
SETTLEMENT_CADENCE=daily
PAYOUT_LINK=https://ipn.eg/S/mahmoudmustafamm/instapay/0qc4FA
PAYMENTS_ENABLED=false

SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_USER=
SMTP_PASS=
MAIL_FROM="DOQ Local <noreply@doq.local>"

ADMIN_BOOTSTRAP_EMAIL=admin@doq.local
ADMIN_BOOTSTRAP_PASSWORD=AdminLocal123!
ADMIN_BOOTSTRAP_FIRST_NAME=DOQ
ADMIN_BOOTSTRAP_LAST_NAME=LocalAdmin
ADMIN_BOOTSTRAP_PHONE=01012345678
ADMIN_BOOTSTRAP_TOTP_SECRET=JBSWY3DPEHPK3PXP

PAYMOB_API_KEY=
PAYMOB_INTEGRATION_ID=
PAYMOB_IFRAME_ID=
PAYMOB_HMAC_SECRET=
PAYMOB_BASE_URL=https://accept.paymob.com/api

BACKUP_ENABLED=false
BACKUP_DIR=/app/backups
MYSQLDUMP_BIN=mysqldump
ENVEOF
    success "Created ${ENV_FILE}"
else
    log "Using existing ${ENV_FILE}"
fi

# 3. Add /etc/hosts entry
step "Configuring /etc/hosts"
if ! grep -q "^127.0.0.1 ${DOMAIN}" /etc/hosts 2>/dev/null; then
    log "Adding ${DOMAIN} to /etc/hosts (requires sudo)..."
    echo "127.0.0.1 ${DOMAIN}" | sudo tee -a /etc/hosts >/dev/null
    success "Added ${DOMAIN} to /etc/hosts"
else
    log "${DOMAIN} already in /etc/hosts"
fi

# 4. Stop any existing containers
step "Stopping any existing containers"
$COMPOSE_CMD down --remove-orphans 2>/dev/null || true
success "Cleaned up"

# 5. Build and start
step "Building and starting containers (db, app, cron, caddy)"
$COMPOSE_CMD up --build -d

# 6. Wait for database
step "Waiting for database"
wait_for_health db

# 7. Wait for app
step "Waiting for application"
wait_for_health app

# 8. Wait for caddy
step "Waiting for Caddy (HTTPS)"
wait_for_health caddy

# 9. Run migrations
step "Running database migrations"
$COMPOSE_CMD exec -T app npm run migrate
success "Migrations complete"

# 10. Bootstrap admin
step "Bootstrapping admin account"
$COMPOSE_CMD exec -T app npm run bootstrap:admin
success "Admin bootstrapped"

# 11. Create test accounts
step "Creating test accounts (customer, chef, delivery, admin)"
$COMPOSE_CMD exec -T -e DOQ_ALLOW_TEST_ACCOUNTS=true -e DOQ_TEST_PASSWORD="${TEST_PASSWORD}" app \
    node scripts/bootstrap-test-accounts.js
success "Test accounts created"

# 12. Verify CSRF endpoint
step "Verifying HTTPS endpoint"
sleep 2
if curl -k -s "https://${DOMAIN}/security/csrf" | grep -q '"token"'; then
    success "HTTPS endpoint responding with CSRF token"
else
    warn "HTTPS endpoint check failed (may need more time)"
fi

# 13. Print summary
step "DEPLOYMENT COMPLETE - Test Accounts Ready"

echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  DOQ Local Production Running at: https://${DOMAIN}           ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo
echo -e "${CYAN}📋 TEST ACCOUNTS (all use password: ${TEST_PASSWORD})${NC}"
echo -e "${CYAN}┌──────────────┬──────────────────────────────────────┬────────────┬──────────┐${NC}"
echo -e "${CYAN}│ Role         │ Email                                │ Phone      │ Status   │${NC}"
echo -e "${CYAN}├──────────────┼──────────────────────────────────────┼────────────┼──────────┤${NC}"
echo -e "${CYAN}│ ${YELLOW}Customer${CYAN}   │ doq-test-customer@example.test       │ 01000000001 │ Approved │${NC}"
echo -e "${CYAN}│ ${YELLOW}Chef${CYAN}       │ doq-test-chef@example.test           │ 01000000002 │ Pending* │${NC}"
echo -e "${CYAN}│ ${YELLOW}Delivery${CYAN}   │ doq-test-delivery@example.test       │ 01000000003 │ Pending* │${NC}"
echo -e "${CYAN}│ ${YELLOW}Admin${CYAN}      │ doq-test-admin@example.test          │ 01000000004 │ Approved │${NC}"
echo -e "${CYAN}├──────────────┼──────────────────────────────────────┼────────────┼──────────┤${NC}"
echo -e "${CYAN}│ ${YELLOW}Admin (Boot)${CYAN}│ ${ADMIN_EMAIL}                    │ 01012345678 │ Approved │${NC}"
echo -e "${CYAN}└──────────────┴──────────────────────────────────────┴────────────┴──────────┘${NC}"
echo
echo -e "${YELLOW}* Chef & Delivery accounts need admin approval:${NC}"
echo -e "  1. Login as admin: https://${DOMAIN}/admin"
echo -e "  2. Email: ${ADMIN_EMAIL}"
echo -e "  3. Password: ${ADMIN_PASS}"
echo -e "  4. 2FA: Use authenticator app with secret: ${ADMIN_TOTP}"
echo -e "  5. Go to Operations → Pending Accounts → Approve"
echo
echo -e "${CYAN}🔗 KEY URLs:${NC}"
echo -e "  • Home:        https://${DOMAIN}"
echo -e "  • Admin:       https://${DOMAIN}/admin"
echo -e "  • Customer:    https://${DOMAIN}/my-orders"
echo -e "  • Chef:        https://${DOMAIN}/users/dashboard"
echo -e "  • Delivery:    https://${DOMAIN}/delivery"
echo -e "  • Auth:        https://${DOMAIN}/auth"
echo -e "  • CSRF Token:  https://${DOMAIN}/security/csrf"
echo -e "  • Categories:  https://${DOMAIN}/categories/api/v1/all"
echo -e "  • Cities:      https://${DOMAIN}/kitchens/api/v1/cities"
echo
echo -e "${CYAN}🛠️  USEFUL COMMANDS:${NC}"
echo -e "  • View logs:      $COMPOSE_CMD logs -f app"
echo -e "  • Stop all:       $COMPOSE_CMD down"
echo -e "  • Stop + wipe DB: $COMPOSE_CMD down -v"
echo -e "  • Restart app:    $COMPOSE_CMD restart app"
echo -e "  • Shell into app: $COMPOSE_CMD exec app sh"
echo -e "  • Run tests:      $COMPOSE_CMD exec app npm test"
echo
echo -e "${YELLOW}⚠️  Browser will show certificate warning (self-signed for .local).${NC}"
echo -e "${YELLOW}   Click 'Advanced' → 'Proceed to doq.local (unsafe)'${NC}"
echo
echo -e "${GREEN}✅ Ready to test! Open https://${DOMAIN} in your browser.${NC}"